# Generated by Django 6.0.2 on 2026-03-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('servicio_interes', models.CharField(blank=True, help_text='Servicio en el que está interesado', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje o consulta del cliente')),
                ('leido', models.BooleanField(default=False, help_text='Marcado por el admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead / Consulta',
                'verbose_name_plural': 'Leads / Consultas',
                'ordering': ('-created_at',),
            },
        ),
    ]
