# Generated by Django 6.0.2 on 2026-03-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('EVENTOS', 'Eventos'), ('INMOBILIARIO', 'Bienes Raíces'), ('TURISMO', 'Turismo'), ('INSPECCION', 'Inspecciones'), ('PRODUCCION', 'Producción Audiovisual')], max_length=20)),
                ('tipo', models.CharField(choices=[('FOTO', 'Fotografía'), ('VIDEO', 'Video')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('enlace', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.')),
                ('imagen', models.CharField(blank=True, help_text='URL de la imagen', max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Portafolio',
                'verbose_name_plural': 'Portafolio',
                'db_table': 'portafolio_portafolio',
                'ordering': ('orden', '-created_at'),
            },
        ),
    ]
