# Generated by Django 5.2.8 on 2026-03-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='destacado_en_portada',
            field=models.BooleanField(default=False, help_text='Mostrar en la portada principal'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='imagen',
            field=models.CharField(blank=True, help_text='URL de la imagen o video', max_length=500),
        ),
    ]
