# Generated by Django 6.0.2 on 2026-03-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('categoria', models.CharField(choices=[('EVENTOS', 'Eventos'), ('INMOBILIARIO', 'Bienes Raíces'), ('TURISMO', 'Turismo'), ('INSPECCION', 'Inspecciones'), ('PRODUCCION', 'Producción Audiovisual')], max_length=20)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del servicio', max_digits=10)),
                ('precio_por_hora', models.DecimalField(decimal_places=2, help_text='Precio adicional por hora', max_digits=10)),
                ('horas_minimas', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de horas a cobrar')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('orden', 'nombre'),
            },
        ),
    ]
