# Generated by Django 5.2.8 on 2026-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
