# Generated by Django 5.2.8 on 2026-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='precio_por_hora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio adicional por hora', max_digits=10),
        ),
    ]
