# Generated by Django 6.0.2 on 2026-03-01 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la reserva')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio (ej: 14:00)')),
                ('hora_fin', models.TimeField(help_text='Hora de fin (ej: 17:00)')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('mensaje', models.TextField(blank=True, help_text='Notas o requerimientos especiales')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('total_cotizado', models.DecimalField(blank=True, decimal_places=2, help_text='Total calculado al momento de la reserva', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='services.service')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ('-fecha', '-hora_inicio'),
                'indexes': [models.Index(fields=['fecha', 'hora_inicio'], name='bookings_bo_fecha_b10c37_idx'), models.Index(fields=['servicio', 'fecha'], name='bookings_bo_servici_dc4a43_idx')],
            },
        ),
    ]
